spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    username: zawadfarhan@gmail.com
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    password: lieifhusgzovtuzx
  datasource:
    testWhileIdle: 'true'
    password: MnoistEkQexL8kIQ4YPcP4xmJ7tCG2H_
    maxActive: '5'
    driver-class-name: org.postgresql.Driver
    username: uevjeixl
    url: jdbc:postgresql://topsy.db.elephantsql.com:5432/uevjeixl
    validationQuery: SELECT 1
  security:
    user:
      password: password
      name: username